### ISSUE TITLE
Ignore ElasticSearch HealthCheck is not working

### ISSUE THREAD

**Issue by NicolasReyDotNet** [jaegertracing/jaeger-client-csharp#186]
## Requirement - what kind of business use case are you trying to solve?
Hi, I would like to avoid HealthCheck of Elasticsearch to be logged into Jaeger, it's spamming my logs. I work in debug with Elastic in a docker compose file, such as my apps which periodically checks its health using the package `AspNetCore.HealthChecks.Elasticsearch`.

## Problem - what in Jaeger blocks you from solving the requirement?
Currenlty I'm not able to fully exclude healthChecks reporting on ElasticSearch using IgnorePatterns.

**ConfigureServies in Startup.cs**
 ```
                // HealthChecks
                services
                    .UseHealthChecks()
                    .AddElasticSearchHC(Configuration);

               // Distributed tracing
               services
                    .AddJaeger(Configuration)
                    .AddOpenTracing()
                    .Configure<AspNetCoreDiagnosticOptions>(options =>
                    {
                        options.Hosting.IgnorePatterns.Add(x =>
                        {
                            return x.Request.Path.ToString().IsIn("/health", "/metrics");
                        });
                    })
                    .Configure<HttpHandlerDiagnosticOptions>(options =>
                    {
                        options.IgnorePatterns.Add(request => new Uri("http://elasticsearch:9200/").IsBaseOf(request.RequestUri));
                    });
```

**My AddJaeger extension**
```
        public static IServiceCollection AddJaeger(this IServiceCollection services, IConfiguration config, string varEnv = "Jaeger")
        {
            var configuration = config.Get<Configuration>(varEnv);
            string serviceName = Assembly.GetEntryAssembly().GetName().Name;

            services.AddSingleton<ITracer>(serviceProvider =>
            {
                var loggerFactory = serviceProvider.GetRequiredService<ILoggerFactory>();
                var endpoint = configuration.Jaeger;

                var remoteReporter = new RemoteReporter.Builder()
                .WithLoggerFactory(loggerFactory) // optional, defaults to no logging
                .WithMaxQueueSize(100)            // optional, defaults to 100
                .WithFlushInterval(TimeSpan.FromSeconds(1)) // optional, defaults to TimeSpan.FromSeconds(1)
                .WithSender(new HttpSender(endpoint))   // optional, defaults to UdpSender("localhost", 6831, 0)
                .Build();

                var loggingReporter = new LoggingReporter(loggerFactory);
                var compositeReporter = new CompositeReporter(remoteReporter, loggingReporter);
                var sampler = new ConstSampler(true);

                ITracer tracer = new Tracer.Builder(serviceName)
                    .WithSampler(sampler)
                    .WithReporter(compositeReporter)
                    .Build();

                // Usefull for OpenTracingSink logger
                GlobalTracer.Register(tracer);

                return tracer;
            });


            return services;
        }
```

**My healthchecks extensions**

```
        public static IHealthChecksBuilder UseHealthChecks(this IServiceCollection services)
            => services.AddHealthChecks().AddCheck("self", () => HealthCheckResult.Healthy()).ForwardToPrometheus();

        public static IHealthChecksBuilder AddElasticSearchHC(this IHealthChecksBuilder healthChecksBuilder, IConfiguration config, string varEnv = "ElasticSearch")
        {
            var configuration = config.Get<ElasticSearch.Configuration>(varEnv);
            return healthChecksBuilder.AddElasticsearch(
                configuration.Nodes.FirstOrDefault()?.NodeUrl,
                name: "ElasticSearchHC",
                failureStatus: HealthStatus.Unhealthy,
                tags: new string[] { "searchengine", "nosql", "elasticsearch" });
        }
```

Basically the HC for Elastic from the package `AspNetCore.HealthChecks.Elasticsearch` does an async Ping to root address :
[Elasticsearch HC : Async Ping](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/83eb960e53178520ba727cb09c2f1156ad124745/src/HealthChecks.Elasticsearch/ElasticsearchHealthCheck.cs#L56)

**And a part of my docker compose file** 
```
version: '3.4'

services:

  itf.microservices.order.projection:
    image: ${DOCKER_REGISTRY-}itfmicroservicesorderprojection
    container_name: itfmicroservicesorderprojection
    build:
      context: .
      dockerfile: src/ITF.Microservices.Order.Projection/src/Dockerfile
    depends_on:
      - elasticsearch


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - ./volumes/elasticsearch:/usr/share/elasticsearch/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

```

When the app is running, the HC are triggered as expected :
```
[14:14:10 DBG] Running health check publishers
[14:14:10 DBG] Running health checks
[14:14:10 DBG] Running health check ElasticSearchHC
[14:14:10 DBG] Ignoring Request http://elasticsearch:9200/
[14:14:10 DBG] Running health check self
[14:14:10 DBG] Health check self completed after 0.2355ms with status Healthy and 'null'
[14:14:10 INF] Span reported: dac8bee78295b292:9884d80fd531c45c:dac8bee78295b292:1 - SendAndReceiveHeaders
[14:14:10 INF] Span reported: dac8bee78295b292:3f94594108f3a391:43197b96753ece13:1 - Deserialize
[14:14:10 INF] Span reported: dac8bee78295b292:43197b96753ece13:dac8bee78295b292:1 - ReceiveBody
[14:14:10 INF] Span reported: dac8bee78295b292:dac8bee78295b292:0000000000000000:1 - CallElasticsearch
[14:14:10 DBG] Health check ElasticSearchHC completed after 22.1559ms with status Healthy and 'null'
[14:14:10 DBG] Health check processing completed after 28.7957ms with combined status Healthy
[14:14:10 DBG] Running health check publisher 'Prometheus.PrometheusHealthCheckPublisher'
[14:14:10 DBG] Health check 'Prometheus.PrometheusHealthCheckPublisher' completed after 0.0874ms
[14:14:10 DBG] Running health check publisher 'App.Metrics.Extensions.HealthChecks.AppMetricsHealthCheckPublisher'
[14:14:10 DBG] Health check 'App.Metrics.Extensions.HealthChecks.AppMetricsHealthCheckPublisher' completed after 0.2536ms
[14:14:10 DBG] Health check publisher processing completed after 31.4883ms
[14:14:11 DBG] Ignoring Request http://jaeger:14268/api/traces?format=jaeger.thrift
[14:14:23 DBG] Ignoring request
```

We can see that a request to `http://elasticsearch:9200/` is correctly ignored, but I still have 4 spans reported, which appear in Jaeger. And I don't know how to get rid of them.
![image](https://user-images.githubusercontent.com/37657851/87798034-c9163680-c84b-11ea-8b96-9539b3da2b96.png)

I hope there is a solution, otherwise I'll have to remove my ElasticSearch HC...
